import {evaluateAutonomy,shadowReserve} from './autonomy.js';
import {initDb,dbEnabled,dbScannerState,persistLots,upsertBusinessRecord,listBusinessRecords,appendLearningEvent,appendAudit,persistentState,getAutonomySettings,autonomyStats} from './db.js';
import http from'node:http';import{analyse,research,runMonitor,ingestLots,scannerState}from'./core.js';const port=process.env.PORT||10000,origin=process.env.ALLOWED_ORIGIN||'*';const send=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json','access-control-allow-origin':origin,'access-control-allow-headers':'content-type,authorization','access-control-allow-methods':'GET,POST,OPTIONS'});res.end(JSON.stringify(data))};const body=req=>new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>12_000_000){reject(new Error('Request too large'));req.destroy()}});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}});req.on('error',reject)});http.createServer(async(req,res)=>{if(req.method==='OPTIONS')return send(res,204,{});let u=new URL(req.url,'http://localhost');try{if(u.pathname==='/api/health')return send(res,200,{ok:true,service:'outlet-vault-worker',aiConfigured:!!process.env.GEMINI_API_KEY,parseConfigured:!!process.env.PARSE_API_KEY,databaseConfigured:dbEnabled(),scannerPersistent:dbEnabled()});if(u.pathname==='/api/analyse'&&req.method==='POST')return send(res,200,{analysis:await analyse(await body(req))});if(u.pathname==='/api/research'&&req.method==='POST')return send(res,200,{research:await research(await body(req))});if(u.pathname==='/api/scanner'&&req.method==='GET'){let db=await dbScannerState();return send(res,200,db?{...scannerState(),...db,persistent:true}:scannerState())}if(u.pathname==='/api/scanner/import'&&req.method==='POST'){let b=await body(req),items=Array.isArray(b)?b:b.lots;if(!Array.isArray(items))return send(res,400,{error:'Provide lots array'});let result=ingestLots(items),persisted=await persistLots(result.lots||[]);return send(res,200,{...result,persisted})}if(u.pathname==='/api/state'&&req.method==='GET')return send(res,200,await persistentState()||{records:[],counts:{records:0,learning:0,audit:0}});
if(u.pathname==='/api/records'&&req.method==='GET')return send(res,200,{records:await listBusinessRecords(u.searchParams.get('type'))});
if(u.pathname==='/api/records'&&req.method==='POST'){let b=await body(req);return send(res,200,await upsertBusinessRecord(b))}
if(u.pathname==='/api/learning'&&req.method==='POST'){let b=await body(req);return send(res,200,await appendLearningEvent(b.eventType,b.lotId,b.data||{}))}
if(u.pathname==='/api/audit'&&req.method==='POST'){let b=await body(req);return send(res,200,await appendAudit(b.action,b.entityType,b.entityId,b.data||{}))}
if(u.pathname==='/api/autonomy/status'&&req.method==='GET')return send(res,200,{settings:await getAutonomySettings(),stats:await autonomyStats(),executionLocked:true});
if(u.pathname==='/api/autonomy/evaluate'&&req.method==='POST')return send(res,200,await evaluateAutonomy(await body(req)));
if(u.pathname==='/api/autonomy/shadow-reserve'&&req.method==='POST')return send(res,200,await shadowReserve(await body(req)));
if(u.pathname==='/api/monitor/run'&&req.method==='POST'){if(!process.env.ADMIN_TOKEN||req.headers.authorization!=='Bearer '+process.env.ADMIN_TOKEN)return send(res,401,{error:'Unauthorized'});return send(res,200,await runMonitor())}return send(res,404,{error:'Not found'})}catch(e){return send(res,e.status||500,{error:e.message||'Server error'})}}).listen(port,async()=>{try{await initDb();console.log('Database '+(dbEnabled()?'ready':'not configured'))}catch(e){console.error('Database init error '+e.message)}console.log('Outlet Vault Worker listening on '+port);if(process.env.SCAN_ON_START==='true'){try{let r=await runMonitor();console.log('SCAN_TEST '+JSON.stringify({parseEnabled:r.johnPye?.enabled,found:r.johnPye?.found,added:r.ingested?.added,updated:r.ingested?.updated,total:r.ingested?.total,candidates:r.candidates?.length,message:r.message}))}catch(e){console.error('SCAN_TEST_ERROR '+e.message)}}});